jobs:
  cache:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      env:
        cuda: 11.6.0
      uses: konduitai/cuda-install/.github/actions/install-cuda-windows@master
    - continue-on-error: true
      env:
        cuda: 11.4.1
      uses: konduitai/cuda-install/.github/actions/install-cuda-windows@master
    - continue-on-error: true
      id: cache-cuda-114
      name: Cache cuda install windows cuda 11.4
      uses: actions/cache@v2
      with:
        key: windows-2019-cuda-11.4
        path: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4
        restore-keys: windows-2019-cuda-11.4
    - continue-on-error: true
      id: cache-cuda-116
      name: Cache cuda install windows cuda 11.6
      uses: actions/cache@v2
      with:
        key: windows-2019-cuda-11.6
        path: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
        restore-keys: windows-2019-cuda-11.6
on:
  repository_dispatch:
    types: trigger-ga___run-gpu-tests-sanity-checks.yml
