jobs:
  linux-x86_64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: AutoModality/action-clean@v1
    - continue-on-error: true
      name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: ./.github/actions/download-dl4j-test-resources-linux
    - continue-on-error: true
      env:
        DEBIAN_FRONTEND: noninteractive
      name: Run cpu tests
      run: 'mvn --version

        cmake --version

        protoc --version

        export OMP_NUM_THREADS=1

        mkdir -p ${GITHUB_WORKSPACE}/resources

        mkdir -p ${GITHUB_WORKSPACE}/cache

        mvn -Djunit.jupiter.execution.parallel.enabled=true -Djunit.jupiter.execution.parallel.mode.default=concurrent
        -Djunit.jupiter.execution.parallel.config.strategy=fixed  -Dorg.nd4j.strumpf.resource.dirs=${GITHUB_WORKSPACE}/resources
        -Dorg.nd4j.test.resources.cache.dir=${GITHUB_WORKSPACE}/cache -DexcludedGroups="long-running-tests,
        large-resources, distributed-systems"  -DskipTestResourceEnforcement=true    clean
        test --fail-never

        mvn -Djunit.jupiter.execution.parallel.enabled=true -Djunit.jupiter.execution.parallel.mode.default=concurrent
        -Djunit.jupiter.execution.parallel.config.strategy=fixed -Dorg.nd4j.strumpf.resource.dirs=${GITHUB_WORKSPACE}/resources
        -Dorg.nd4j.test.resources.cache.dir=${GITHUB_WORKSPACE}/cache -Dgroups="long-running-tests,
        large-resources, distributed-systems"   -Dtest.offheap.size=14g -Dtest.heap.size=6g  -Dsurefire.parallel.forcedTimeout=500
        -Dsurefire.parallel.timeout=500  -Dsurefire.timeout=200 -Dsurefire.exitTimeout=500
        test --fail-never -rf :nd4j

        '
      shell: bash
on:
  repository_dispatch:
    types: trigger-ga___run-cpu-integration-tests.yml
