jobs:
  linux-x86_64:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: AutoModality/action-clean@v1
    - continue-on-error: true
      name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: ./.github/actions/download-dl4j-test-resources-linux
    - continue-on-error: true
      env:
        DEBIAN_FRONTEND: noninteractive
      name: Run cpu tests
      run: 'mvn --version

        cmake --version

        export OMP_NUM_THREADS=2

        mvn   -DskipTestResourceEnforcement=true -Dlibnd4j.build=debug -Dlibnd4j.sanitize=ON
        clean test'
      shell: bash
on:
  repository_dispatch:
    types: trigger-ga___run-cpu-tests-sanity-checks.yml
